"""Add content management tables

Revision ID: 5d883285e4df
Revises: 20251120_000001_add_cart_item_series_and_color_fields
Create Date: 2026-02-25 05:28:55.914337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '5d883285e4df'
down_revision: Union[str, Sequence[str], None] = '20251120_000001_add_cart_item_series_and_color_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_check_check_number'))
        batch_op.drop_index(batch_op.f('ix_check_id'))

    op.drop_table('check')
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_invoice_number'))

    op.drop_table('invoice')
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cart_customer_id'))
        batch_op.drop_index(batch_op.f('ix_cart_id'))

    op.drop_table('cart')
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_site_settings_id'))
        batch_op.drop_index(batch_op.f('ix_site_settings_key'))

    op.drop_table('site_settings')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_id'))

    op.drop_table('user')
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_id'))
        batch_op.drop_index(batch_op.f('ix_customer_person_code'))

    op.drop_table('customer')
    with op.batch_alter_table('bankaccount', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bankaccount_id'))

    op.drop_table('bankaccount')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_code'))
        batch_op.drop_index(batch_op.f('ix_product_id'))

    op.drop_table('product')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_id'))
        batch_op.drop_index(batch_op.f('ix_category_name'))

    op.drop_table('category')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_id'))
        batch_op.drop_index(batch_op.f('ix_articles_slug'))

    op.drop_table('articles')
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_images_id'))
        batch_op.drop_index(batch_op.f('ix_product_images_product_id'))

    op.drop_table('product_images')
    with op.batch_alter_table('inventorytransaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventorytransaction_id'))

    op.drop_table('inventorytransaction')
    with op.batch_alter_table('invoiceitem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoiceitem_id'))

    op.drop_table('invoiceitem')
    with op.batch_alter_table('cartitem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cartitem_id'))

    op.drop_table('cartitem')
    with op.batch_alter_table('sliders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sliders_id'))

    op.drop_table('sliders')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sliders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('image_url', sa.VARCHAR(), nullable=False),
    sa.Column('link', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('display_order', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sliders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sliders_id'), ['id'], unique=False)

    op.create_table('cartitem',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('cart_id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=False),
    sa.Column('unit', sa.VARCHAR(), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('selected_series', sqlite.JSON(), nullable=True),
    sa.Column('selected_color', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cartitem', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cartitem_id'), ['id'], unique=False)

    op.create_table('invoiceitem',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('invoice_id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=False),
    sa.Column('unit', sa.VARCHAR(), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('rolls_count', sa.REAL(), nullable=True),
    sa.Column('pieces_per_roll', sa.REAL(), nullable=True),
    sa.Column('detailed_rolls', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoiceitem', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoiceitem_id'), ['id'], unique=False)

    op.create_table('inventorytransaction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('change_quantity', sa.FLOAT(), nullable=False),
    sa.Column('reason', sa.VARCHAR(length=16), nullable=False),
    sa.Column('reference_id', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventorytransaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventorytransaction_id'), ['id'], unique=False)

    op.create_table('product_images',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('image_url', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_images_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_images_id'), ['id'], unique=False)

    op.create_table('articles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('slug', sa.VARCHAR(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('cover_image_url', sa.VARCHAR(), nullable=True),
    sa.Column('excerpt', sa.TEXT(), nullable=True),
    sa.Column('is_published', sa.BOOLEAN(), nullable=False),
    sa.Column('views_count', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_articles_slug'), ['slug'], unique=1)
        batch_op.create_index(batch_op.f('ix_articles_id'), ['id'], unique=False)

    op.create_table('category',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('image_url', sa.VARCHAR(), nullable=True),
    sa.Column('visible', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_name'), ['name'], unique=1)
        batch_op.create_index(batch_op.f('ix_category_id'), ['id'], unique=False)

    op.create_table('product',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('category', sa.VARCHAR(), nullable=False),
    sa.Column('unit', sa.VARCHAR(), nullable=False),
    sa.Column('colors', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_available', sa.BOOLEAN(), nullable=False),
    sa.Column('shrinkage', sa.VARCHAR(), nullable=True),
    sa.Column('visible', sa.BOOLEAN(), nullable=False),
    sa.Column('width', sa.VARCHAR(), nullable=True),
    sa.Column('usage', sa.VARCHAR(), nullable=True),
    sa.Column('season', sa.VARCHAR(), nullable=True),
    sa.Column('weave_type', sa.VARCHAR(), nullable=True),
    sa.Column('is_series', sa.BOOLEAN(), nullable=False),
    sa.Column('series_inventory', sqlite.JSON(), nullable=True),
    sa.Column('series_numbers', sqlite.JSON(), nullable=True),
    sa.Column('available_colors', sqlite.JSON(), nullable=True),
    sa.Column('color_inventory', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_code'), ['code'], unique=False)

    op.create_table('bankaccount',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('bank_name', sa.VARCHAR(), nullable=False),
    sa.Column('account_number', sa.VARCHAR(), nullable=False),
    sa.Column('iban', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bankaccount', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bankaccount_id'), ['id'], unique=False)

    op.create_table('customer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('person_code', sa.VARCHAR(), nullable=True),
    sa.Column('person_type', sa.VARCHAR(), nullable=True),
    sa.Column('first_name', sa.VARCHAR(), nullable=False),
    sa.Column('last_name', sa.VARCHAR(), nullable=False),
    sa.Column('company_name', sa.VARCHAR(), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('phone', sa.VARCHAR(), nullable=True),
    sa.Column('mobile', sa.VARCHAR(), nullable=True),
    sa.Column('city', sa.VARCHAR(), nullable=True),
    sa.Column('province', sa.VARCHAR(), nullable=True),
    sa.Column('current_balance', sa.FLOAT(), server_default=sa.text('(0.0)'), nullable=False),
    sa.Column('balance_notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('excel_data', sa.TEXT(), nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_person_code'), ['person_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_id'), ['id'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(), nullable=False),
    sa.Column('last_name', sa.VARCHAR(), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=10), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=1)

    op.create_table('site_settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.VARCHAR(), nullable=False),
    sa.Column('value', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_site_settings_key'), ['key'], unique=1)
        batch_op.create_index(batch_op.f('ix_site_settings_id'), ['id'], unique=False)

    op.create_table('cart',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('customer_name', sa.VARCHAR(), nullable=False),
    sa.Column('customer_phone', sa.VARCHAR(), nullable=False),
    sa.Column('customer_email', sa.VARCHAR(), nullable=True),
    sa.Column('customer_address', sa.VARCHAR(), nullable=True),
    sa.Column('notes', sa.VARCHAR(), nullable=True),
    sa.Column('total_amount', sa.FLOAT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=8), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('customer_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cart_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cart_customer_id'), ['customer_id'], unique=False)

    op.create_table('invoice',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('invoice_number', sa.VARCHAR(), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('created_by', sa.INTEGER(), nullable=False),
    sa.Column('subtotal', sa.FLOAT(), nullable=False),
    sa.Column('total', sa.FLOAT(), nullable=False),
    sa.Column('payment_type', sa.VARCHAR(length=5), nullable=False),
    sa.Column('payment_breakdown', sqlite.JSON(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=18), nullable=False),
    sa.Column('tracking_info', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_invoice_number'), ['invoice_number'], unique=1)
        batch_op.create_index(batch_op.f('ix_invoice_id'), ['id'], unique=False)

    op.create_table('check',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('check_number', sa.VARCHAR(), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('issue_date', sa.VARCHAR(), nullable=False),
    sa.Column('due_date', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=11), nullable=False),
    sa.Column('related_invoice_id', sa.INTEGER(), nullable=True),
    sa.Column('attachments', sqlite.JSON(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['related_invoice_id'], ['invoice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('check', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_check_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_check_check_number'), ['check_number'], unique=False)

    # ### end Alembic commands ###
